{
 "title": "router - Operational Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "router endpoint request count per day",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(api_http_response_code_total{exported_endpoint=\"router\",identifier=\"200\", service=\"swift-router-kogito-quarkus\"}[1d]))",
     "legendFormat": "Quarkus"
    },
    {
     "expr": "sum(increase(api_http_response_code_total{exported_endpoint=\"router\",identifier=\"200\", service=\"swift-router-kogito-springboot\"}[1d]))",
     "legendFormat": "Springboot"
    }
   ]
  },
  {
   "title": "Average requests per minute to router endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(api_http_response_code_total{exported_endpoint=\"router\", service=\"swift-router-kogito-quarkus\"}[1m])) ",
     "legendFormat": "Quarkus"
    },
    {
     "expr": "sum(increase(api_http_response_code_total{exported_endpoint=\"router\", service=\"swift-router-kogito-springboot\"}[1m])) ",
     "legendFormat": "Springboot"
    }
   ]
  },
  {
   "title": "Execution time quantiles for endpoint router",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(api_execution_elapsed_seconds_sum{exported_endpoint=\"router\", service=\"swift-router-kogito-quarkus\"}[1m]))/sum(increase(api_execution_elapsed_seconds_count{exported_endpoint=\"router\",service=\"swift-router-kogito-quarkus\"}[1m]))",
     "legendFormat": "Quarkus"
    },
    {
     "expr": "sum(increase(api_execution_elapsed_seconds_sum{exported_endpoint=\"router\", service=\"swift-router-kogito-springboot\"}[1m]))/sum(increase(api_execution_elapsed_seconds_count{exported_endpoint=\"router\",service=\"swift-router-kogito-springboot\"}[1m]))",
     "legendFormat": "Springboot"
    }
   ]
  },
  {
   "title": "router endpoint status code responses per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (identifier) (increase(api_http_response_code_total{exported_endpoint=\"router\", service=\"swift-router-kogito-quarkus\"}[1m]))",
     "legendFormat": "Quarkus"
    },
    {
     "expr": "sum by (identifier) (increase(api_http_response_code_total{exported_endpoint=\"router\", service=\"swift-router-kogito-springboot\"}[1m]))",
     "legendFormat": "Springboot"
    }
   ]
  },
  {
   "title": "Exceptions details",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (identifier) (increase(api_http_stacktrace_exceptions_total{exported_endpoint=\"router\"}[1d]))"
    }
   ]
  },
  {
   "title": "Exception count per day",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(api_http_stacktrace_exceptions_total{exported_endpoint=\"router\"}[1d]))"
    }
   ]
  }
 ]
}