apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: swift-router-kogito-springboot
  name: swift-router-kogito-springboot
spec:
  endpoints:
  - path: /metrics
    targetPort: 8080
    scheme: http
  namespaceSelector:
    matchNames:
    - swift-router
  selector:
    matchLabels:
      app: swift-router-kogito-springboot
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: swift-router-kogito-quarkus
  name: swift-router-kogito-quarkus
spec:
  endpoints:
  - path: /metrics
    targetPort: 8080
    scheme: http
  namespaceSelector:
    matchNames:
    - swift-router
  selector:
    matchLabels:
      app: swift-router-kogito-quarkus