apiVersion: batch/v1
kind: Job
metadata:
  name: swift-router-remote-client-quarkus-job
  namespace: swift-router-prod
spec:
  selector: {}
  template:
    metadata:
      name: swift-router-remote-client-quarkus-job
    spec:
      parallelism: 1 
      containers:
        - name: swift-router-remote-client
          image: image-registry.openshift-image-registry.svc:5000/swift-router-prod/swift-router-remote-client@sha256:5c9d37c9f668f468626cd9a8da044a9b11249e75ca782710ab8d5e1b2cd8e632
          command:
            - java
            - '-Dquarkus.http.host=0.0.0.0'
            - '-Djava.util.logging.manager=org.jboss.logmanager.LogManager'
            - '-jar'
            - /deployments/quarkus-run.jar
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: SWIFTQUARKUS_URL
              valueFrom:
                configMapKeyRef:
                  name: swift-router-cm
                  key: SwiftQuarkus_URL
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: swift-router-cm
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: JAVA_APP_JAR
              value: /deployments/quarkus-run.jar
            - name: NB_MESSAGES
              value: '1000'
            - name: SERVICE_TYPE
              value: 'quarkus'   
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: swift-router-remote-client-springboot-job
  namespace: swift-router-prod
spec:
  selector: {}
  template:
    metadata:
      name: swift-router-remote-client-springboot-job
    spec:
      parallelism: 1 
      containers:
        - name: swift-router-remote-client
          image: image-registry.openshift-image-registry.svc:5000/swift-router-prod/swift-router-remote-client@sha256:5c9d37c9f668f468626cd9a8da044a9b11249e75ca782710ab8d5e1b2cd8e632
          command:
            - java
            - '-Dquarkus.http.host=0.0.0.0'
            - '-Djava.util.logging.manager=org.jboss.logmanager.LogManager'
            - '-jar'
            - /deployments/quarkus-run.jar
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: SWIFTSPRINGBOOT_URL
              valueFrom:
                configMapKeyRef:
                  name: swift-router-cm
                  key: SwiftSpringBoot_URL
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: swift-router-cm
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: NB_MESSAGES
              value: '1000'
            - name: SERVICE_TYPE
              value: 'springboot'
            - name: JAVA_APP_JAR
              value: /deployments/quarkus-run.jar            
      restartPolicy: Never